# 課題チェック

In [1]:
import numpy as np

## answer

In [53]:
# 答えを書く欄
Q1_1 = 'ABC'
Q1_2 = 'AC'
Q1_3 = 'AC'
Q1_4 = 'ABC'

import numpy as np


def Q2(A, B, C, x):
    """
    Description: 
        matrix-vector calculation
    Arguments: 
        A: matrix l by m (2-dimensional numpy array)
        B: matrix m by n (2-dimensional numpy array)
        C: matrix n by l (2-dimensional numpy array)
        x: vector size m (1-dimensional numpy array)
    Return: 
        A_ik x_k B_kj - C_ji (k-index summed [0 to m-1])
    """
    # CODEME
    return np.einsum('ik,k,kj->ij', A, x, B) - C.T


def Q3(x, a):
    """
    Description:
        sorting function
    Arguments:
        x: 2-dimensional numpy array
    Return:
        numpy array with the same shape as x
    """
    # CODEME
    def distance(_a, _b):
        return np.sqrt(np.power(_a -_b, 2).sum())
    
    index = np.argsort(np.array([distance(x[i], a) for i in range(x.shape[0])]))
    
    return x[index]


def Q4(M, N, x0, x1, y0, y1):
    """
    Description:
        sum over cropped region
    Arguments:
        M, N, x0, x1, y0, y1: integer
    Return:
        the sum over region in (x0, x1), (y0, y1)
    """
    # CODEME
    A = np.arange(M*N).reshape(N, M)
    a = A[y0:y1+1, x0:x1+1]

    return a.sum()


def Q5_1(x):
    """
    Description:
        get one-hot expression from category expression
    Arguments:
        x: one-dimensional numpy array, data type integer 
    Return:
        numpy array, one-hot expression of x
    """
    # CODEME
    columns = np.unique(x)
    X = np.zeros([x.shape[0], len(columns)])
    for i, column in enumerate(columns):
        X[np.where(x==column), i] = 1
    return X


def Q5_2(x):
    """
    Description:
        get category expression from one-hot expression
    Arguments:
        x: numpy array, one-hot expression
    Return:
        one-dimensional numpy array, category expression of x
    """
    # CODEME
    return x.argmax(axis=1)


def Q6(m, n):
    """
    Description:
        produce multiplication tables m by n
    Arguments:
        m, n: integer
    Return:
        numpy array with shape (m,n)
    """
    # CODEME
    a = np.arange(1, n+1)[:, np.newaxis]
    b = np.arange(1, m+1)[np.newaxis, :]
    return a.dot(b)


def Q7(x):
    """
    Arguments:
        x: numpy array 1 dimension
    Return:
        numpy array 1 dimension
        each component is x[i+1] - x[i]  
    """
    # CODEME
    return np.array([x[i+1] - x[i] for i in range(len(x)-1)])

In [2]:
print(np.arange(10)//2)
print((np.arange(5)[:,np.newaxis]*(1,1)).flatten())
print(np.array([(i,i) for i in range(5)]).flatten())

[0 0 1 1 2 2 3 3 4 4]
[0 0 1 1 2 2 3 3 4 4]
[0 0 1 1 2 2 3 3 4 4]


#### np.newaxis

大きさが1の次元を追加する

In [12]:
np.arange(5)[:,np.newaxis]*(1,1)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [13]:
x = np.arange(10)
x * (x%2==1)

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [14]:
np.array([i if i%2==0 else 0 for i in range(10)])

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [15]:
np.arange(10) * np.tile([0,1], 5)

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

#### np.tile
配列aをタイル状に並べる

In [16]:
2**(np.arange(5))

array([ 1,  2,  4,  8, 16])

In [17]:
np.apply_along_axis(np.square, 0, (np.arange(5)))

array([ 0,  1,  4,  9, 16])

In [18]:
x = [1]
[x.append(x[i]*2) for i in range(4)]    
np.array(x)

array([ 1,  2,  4,  8, 16])

In [19]:
np.sign(np.arange(10) - 4.5)

array([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.])

In [20]:
np.concatenate([-np.ones(5), np.ones(5)])

array([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
(np.arange(10) > 4.5) * 2.0 - 1

array([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.])


- einsum  
  テンソル積一般を表現でき、表現力の意味では最も強力です。（byアインシュタインの縮約規則）
  
  このeinsumがあればtraceやtransposeはもちろん、これまでに扱ったmatmulやtensordotも実現可能できてしまいます。（※要使い分け）
  
  重要なのは、einsumでは2テンソル間の演算だけでなく3つ以上のテンソル間の演算も一度に実現可能であることでしょう。
  
  なお、積和の式が与えられた時のeinsumの表現は一般に次のようにして得ることができます（例：$c_{ik} = \sum_{j} a_{ij}\times b_{jk}$）
  1. 変数名を消す（例：$ik = \sum_{j} ij \times jk$）
  2. 積（$\times$）をカンマで置き換える（例：$ik = \sum_{j} ij, jk$）
  3. シグマを消す（例：$ik = ij, jk$）
  4. 左辺右辺を反転させ、等号を->にする（例：$ij, jk -> ik$）
  
  （例）
  
  `np.einsum('ij,jk->ik', A, B)`：行列積$\sum_{j} a_{ij}b_{jk}$
  
  `np.einsum('i,i->', v, u)`：ベクトルの内積$\sum_{i} v_{i}u_{i}$

# Q2
以下の関数を実装してください。
$$
\sum_k A_{ik} x_k B_{kj} - C_{ji}
$$


例えば
```
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[2,3],[1,2]])
x = np.array([-1, 1, 3])
```
の場合この関数は
```
array([[ 48,  59],
       [ 98, 118]])
```
を与えます。

In [44]:
def Q2(A, B, C, x):
    """
    Description: 
        matrix-vector calculation
    Arguments: 
        A: matrix l by m (2-dimensional numpy array)
        B: matrix m by n (2-dimensional numpy array)
        C: matrix n by l (2-dimensional numpy array)
        x: vector size m (1-dimensional numpy array)
    Return: 
        A_ik x_k B_kj - C_ji (k-index summed [0 to m-1])
    """
    # CODEME
    return np.einsum('ik,k,kj->ij', A, x, B) - C.T

In [23]:
# einsum
A = np.arange(25).reshape(5,5)
b = np.arange(5)
b2 = np.arange(5) + 1

In [25]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# 対角成分
print(np.einsum('ii->i', A))    # c_{i} = a_{ii}
print(np.diag(A))
print()

[ 0  6 12 18 24]
[ 0  6 12 18 24]



In [26]:
# トレース
print(np.einsum('ii', A))   # C = \sum_{i} a_{ii}
print(np.trace(A))
print()

60
60



In [45]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[2, 3], [1, 2]])
x = np.array([-1, 1, 3])

Q2(A, B, C, x) 


array([[ 48,  59],
       [ 98, 118]])

# Q3
x, a が shape = (N,M), (M,) の numpy array として与えらえれています。

xの各要素をについて、a に近い順に並べ替えて出力する関数を書いてください。

ここで、a, b が近いとはノルム $ \left | a - b \right| = \sqrt{\sum_i \left(a_i - b_i\right)^2}  $ が小さい事を意味します。

例
```
x = np.array([[87, 14], [81, 62], [81, 18], [ 8, 63], [51, 15], [38, 63], [80, 36], [69, 78], [26, 9]])
a = np.array([25, 75]) 
```
として x, y が与えられた時、この関数は
```
array([[38, 63],
       [ 8, 63],
       [69, 78],
       [81, 62],
       [51, 15],
       [26,  9],
       [80, 36],
       [81, 18],
       [87, 14]])
```
を返します

In [47]:
def Q3(x, a):
    """
    Description:
        sorting function
    Arguments:
        x: 2-dimensional numpy array
    Return:
        numpy array with the same shape as x
    """
    # CODEME
    def distance(_a, _b):
        return np.sqrt(np.power(_a-_b, 2))
    
    index = np.argsort(np.array([distance(x[i], a) for i in range(x.shape[0])]))
    return x[index]

# Q5

category 表現から one-hot 表現を得る関数を作成してください。

またその逆関数も作成して下さい。

category表現とone-hot表現は例えば以下のような関係です。
```
category　[0, 1, 2, 1, 0, 2, 2, 1, 0]
```
```
one-hot
[[ 1., 0., 0.],
[ 0., 1., 0.],
[ 0., 0., 1.],
[ 0., 1., 0.],
[ 1., 0., 0.],
[ 0., 0., 1.],
[ 0., 0., 1.],
[ 0., 1., 0.],
[ 1., 0., 0.]]
```
今、category表現はintegerとして、
one-hotのスロット数はcategory表現の最大値+1とします。(例ではcategoryの最大値が２でone-hotは３スロット)